FROM golang:1.18.1-alpine as builder
WORKDIR /app
COPY go.* ./
RUN go mod download -x
COPY . .
RUN GO111MODULE=on GOARCH=amd64 GOOS=linux CGO_ENABLED=0 GOFLAGS="-buildvcs=false" go build -ldflags="-w -s" -o /app/application

FROM alpine:3.16

WORKDIR /app
COPY --from=builder /app/application /app/application
COPY --from=builder /app/.env /app/.env
# CMD ["/app/application"]

ENTRYPOINT ["./application"]
EXPOSE 8090
